apiVersion: v1
kind: Service
metadata:
  name: {{ include "blue-green.fullname" . }}-blue
spec:
  selector:
    app: green
  ports:
    - protocol: TCP
      port: {{ .Values.blue.service.port }}
      targetPort: {{ .Values.blue.service.targetPort }}
  type: {{ .Values.blue.service.type }}

